project_id = "qfprslmwsuetqabexwkf"

[functions.convite-visitante]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.gerar-noticias]
verify_jwt = false

[functions.notify-avaliacao]
verify_jwt = false