workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Archive iOS
        script: |
          cd ios/App
          xcodebuild \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=AR9789SH9Q \
            PRODUCT_BUNDLE_IDENTIFIER=app.morador.app \
            CODE_SIGN_STYLE=Automatic \
            archive

    artifacts:
      - ios/App/build/**/*.xcarchive
