workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: NewKey
    environment:
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Codemagic Code Signing
        script: |
          # 1. Cria o chaveiro temporário no servidor da Codemagic
          keychain initialize
          
          # 2. Usa a NewKey para gerar o certificado e o perfil (.p12 e .mobileprovision)
          # Isso resolve o erro de "private key" criando uma nova no ato
          app-store-connect fetch-signing-files "app.morador.app" \
            --type IOS_APP_STORE \
            --create
            
          # 3. Instala tudo o que foi gerado no chaveiro para o Xcode enxergar
          keychain add-certificates
      - name: Archive
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xarchive \
            archive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=AR9789SH9Q
    publishing:
      app_store_connect:
        auth: integration