workflows:
  ios-release:
    name: iOS Release Build
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Install pods
        script: |
          cd ios/App
          pod install
          cd ../../

      - name: Build IPA (automatic signing)
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App \
            --clean

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: YBD8XAS39B
        key_id: YBD8XAS39B
        issuer_id: 61436aad-2e28-4060-b6a0-23761165b8f0
