workflows:
  ios-release:
    name: iOS Release Build
    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../../

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa
