workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest

    integrations:
      app_store_connect: NewKey

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Archive iOS
        script: |
          cd ios/App
          xcode-project use-profiles
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive

    artifacts:
      - ios/App/build/**/*.xcarchive
