workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: morador.app
    environment:
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Archive
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme morador-hub \
            -configuration Release \
            -archivePath build/App.xarchive \
            archive \
            -allowProvisioningUpdates
    publishing:
      app_store_connect:
        auth: integration