workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: NewKey
    environment:
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Archive
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xarchive \
            -allowProvisioningUpdates \
            -authenticationKeyID "J6P4Z38793" \
            -authenticationKeyIssuerID "61436aad-2e28-4060-b6a0-23761165b8f0" \
            -authenticationKeyPath $APP_STORE_CONNECT_AUTH_KEY_PATH \
            archive \
            DEVELOPMENT_TEAM=AR9789SH9Q
    publishing:
      app_store_connect:
        auth: integration