workflows:
  ios-release:
    name: iOS Release Build

    environment:
      xcode: latest
      groups:
        - app_store_credentials

      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App \
            --archive-xcargs "DEVELOPMENT_TEAM=D46N5J26Z5"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: api_key
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: true
