workflows:

  android-release:
    name: Android Release Build
    environment:
      node: 22
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab



  ios-release:
    name: iOS Release Build
    environment:
      node: 22
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install || true
          cd ..

      - name: Create Export Options Plist
        script: |
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>destination</key>
              <string>export</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

      - name: Build IPA
        script: |
          if [ -d "ios/App/App.xcworkspace" ]; then
            xcode-project build-ipa \
              --workspace ios/App/App.xcworkspace \
              --scheme App \
              --archive-xcargs "CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM=D46N5J26Z5" \
              --export-options-plist export_options.plist
          else
            xcode-project build-ipa \
              --project ios/App/App.xcodeproj \
              --scheme App \
              --archive-xcargs "CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM=D46N5J26Z5" \
              --export-options-plist export_options.plist
          fi

    artifacts:
      - build/ios/ipa/*.ipa
