workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: NewKey
    environment:
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Codemagic Code Signing
        script: |
          keychain initialize
          # Removida a flag --save-keys que causou o erro
          app-store-connect fetch-signing-files "app.morador.app" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
      - name: Archive
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xarchive \
            archive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=AR9789SH9Q
    publishing:
      app_store_connect:
        auth: integration