scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Build IPA
        script: |
          # Forçando o Xcode a aceitar a assinatura manual via CLI
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xarchive \
            archive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=AR9789SH9Q \
            CODE_SIGN_IDENTITY="Apple Distribution"