workflows:
  ios-release:
    name: iOS Release Build

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Build IPA
        script: |
          cd ios/App
          xcode-project build-ipa \
            --project App.xcodeproj \
            --scheme App

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
