workflows:
  ios-release:
    name: iOS Production Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: NewKey
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Web Project
        script: npm run build
      - name: Capacitor Sync
        script: npx cap sync ios
      - name: Build IPA
        script: |
          xcode-project use-profiles --bundle-id app.morador.app
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App \
            --export-method app-store
    publishing:
      app_store_connect:
        auth: integration