workflows:
  android-release:
    name: Android Release Build
    environment:
      node: 22
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
