workflows:
  capacitor-workflow:
    name: Android + iOS Build
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest
      java: 21

    ios_signing:
      distribution_type: app_store
      bundle_identifier: app.morador.app

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios
          npx cap sync android

      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Build iOS Archive
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App \
            --archive-xcargs "CODE_SIGN_STYLE=Automatic"

    artifacts:
      - android/app/build/outputs/**/*.aab
      - build/ios/ipa/*.ipa
