workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: morador.app
    environment:
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Archive
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xarchive \
            archive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=SEU_TEAM_ID_AQUI \
            -authenticationKeyID J6P4Z38793 \
            -authenticationKeyIssuerID SEU_ISSUER_ID_AQUI \
            -authenticationKeyPath $APP_STORE_CONNECT_AUTH_KEY_PATH
    publishing:
      app_store_connect:
        auth: integration