workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: NewKey
    environment:
      xcode: latest
      vars:
        BUNDLE_ID: "app.morador.app"
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Code Signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          # Este comando abaixo é o que "conserta" o projeto para você
          xcode-project use-profiles --bundle-id "$BUNDLE_ID"
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App
    publishing:
      app_store_connect:
        auth: integration