workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    environment:
      node: 22
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app
    integrations:
      app_store_connect: NewKey
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Archive iOS
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=AR9789SH9Q
    artifacts:
      - ios/App/build/**/*.xcarchive