workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      xcode: latest
      groups:
        - app_store_credentials

    ios_signing:
      distribution_type: app_store
      bundle_identifier: app.morador.app

    scripts:
      - npm install
      - npm run build
      - npx cap sync ios

      - xcodebuild -project ios/App/App.xcodeproj -scheme App -configuration Release -archivePath ios/build/App.xcarchive archive
      - xcodebuild -exportArchive -archivePath ios/build/App.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath ios/build

    artifacts:
      - ios/build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
