workflows:
  capacitor-workflow:
    name: Android + iOS Build
    max_build_duration: 60

    environment:
      node: 18
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync

      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Build iOS Archive
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/App.xcarchive \
          archive

    artifacts:
      - android/app/build/outputs/**/*.aab
      - ios/build/**/*.xcarchive
