workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: NewKey
    environment:
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Build and Sign IPA
        script: |
          # Comando corrigido: workspace/project deve vir por último
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --bundle-id "app.morador.app"
    publishing:
      app_store_connect:
        auth: integration