workflows:

  android-release:
    name: Android Release Build
    environment:
      node: 22
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab



  ios-release:
    name: iOS Release Build
    environment:
      node: 22
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install || true
          cd ..

      - name: Detect workspace and build IPA
        script: |
          if [ -d "ios/App/App.xcworkspace" ]; then
            echo "Using ios/App/App.xcworkspace"
            xcode-project build-ipa \
              --workspace ios/App/App.xcworkspace \
              --scheme App
          elif [ -d "ios/App.xcworkspace" ]; then
            echo "Using ios/App.xcworkspace"
            xcode-project build-ipa \
              --workspace ios/App.xcworkspace \
              --scheme App
          else
            echo "Using ios/App/App.xcodeproj"
            xcode-project build-ipa \
              --project ios/App/App.xcodeproj \
              --scheme App
          fi

    artifacts:
      - build/ios/ipa/*.ipa
