workflows:
  # ========================================
  # WORKFLOW iOS
  # ========================================
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    environment:
      node: 22
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app
    integrations:
      app_store_connect: NewKey
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  # ========================================
  # WORKFLOW ANDROID
  # ========================================
  android-workflow:
    name: Android Production Build
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      node: 22
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor Android
        script: |
          npx cap sync android
      - name: Set up code signing
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Build Android AAB
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - ia.oliveira.click@gmail.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal