workflows:

  android-build:
    name: Android Build (Capacitor)
    max_build_duration: 60

    environment:
      node: 22
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab



  ios-build:
    name: iOS Build (Signed - App Store)
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Archive iOS
        script: |
          cd ios/App
          xcodebuild \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive

    artifacts:
      - ios/App/build/**/*.xcarchive
