workflows:
  ios-release:
    name: iOS Release (Capacitor)
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      xcode: latest
      groups:
        - app_store_credentials

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Build iOS
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -archivePath App.xcarchive \
          archive

      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
          -archivePath App.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath build

    artifacts:
      - ios/App/build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
