scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Fetch Signing Files
        script: |
          # Inicializa o chaveiro para guardar a nova chave privada
          keychain initialize
          
          # Gera um novo certificado e perfil, criando a chave privada no servidor
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
            
          # Registra o certificado gerado no sistema de build
          keychain add-certificates
      - name: Build IPA
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xarchive \
            archive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=AR9789SH9Q \
            CODE_SIGN_IDENTITY="Apple Distribution"