@'
workflows:
  build-ios-ipa:
    name: Build Resident Hub IPA
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_connect   # ajuste se o seu grupo de variáveis de ambiente no Codemagic tiver nome diferente
    scripts:
      - flutter pub get
      - flutter build ipa --release --export-options-plist=ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
'@ | Out-File -FilePath codemagic.yaml -Encoding utf8 -Force