workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2

    environment:
      xcode: latest
      groups:
        - app_store_credentials

    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release -archivePath build/App.xcarchive archive
      - xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath build

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
