workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest

    integrations:
      app_store_connect: NewKey

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Inject development team
        script: |
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Automatic;\n\t\t\t\tDEVELOPMENT_TEAM = AR9789SH9Q;/' ios/App/App.xcodeproj/project.pbxproj

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Archive iOS
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive

    artifacts:
      - ios/App/build/**/*.xcarchive
