workflows:
  ios-release:
    name: iOS Release

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Archive app
        script: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            DEVELOPMENT_TEAM=D46N5J26Z5 \
            CODE_SIGN_STYLE=Automatic

      - name: Export IPA
        script: |
          mkdir -p build/ipa
          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa
