workflows:
  capacitor-workflow:
    name: Android + iOS Build
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync

      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Build iOS Archive (SPM)
        script: |
          cd ios/App
          xcodebuild \
          -scheme App \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/App.xcarchive \
          DEVELOPMENT_TEAM=AR9789SH9Q \
          CODE_SIGN_STYLE=Automatic \
          archive

    artifacts:
      - android/app/build/outputs/**/*.aab
      - ios/App/build/**/*.xcarchive
