workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: Codemagic

    environment:
      xcode: latest

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Build iOS archive
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build

    artifacts:
      - build/*.ipa

    publishing:
      app_store_connect:
        submit_to_testflight: true
