workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    environment:
      node: 22
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.morador.app
    integrations:
      app_store_connect: NewKey
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true