workflows:
  ios-release:
    name: iOS Manual Build
    integrations:
      app_store_connect: NewKey
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "app.morador.app"
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - name: Build IPA
        script: |
          # Encontrando o caminho real da chave de autenticação no servidor
          AUTH_KEY_PATH=$(find /Users/builder/Library/MobileDevice/Certificates -name "AuthKey_*.p8" | head -n 1)
          
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xarchive \
            archive \
            -allowProvisioningUpdates \
            -authenticationKeyID "J6P4Z38793" \
            -authenticationKeyIssuerID "61436aad-2e28-4060-b6a0-23761165b8f0" \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            DEVELOPMENT_TEAM=AR9789SH9Q
    publishing:
      app_store_connect:
        auth: integration